version: '3'
services:
  nginx-rtmp:
    build: .
    image: nginx-rtmp:v1.0
    container_name: nginx-rtmp
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    volumes:
      #- ./certs:/opt/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data:/opt/data/hls
    #command: ["nginx", "-g", "daemon off;"]
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "10"
